version: "2"
services:
  core:
    user: "0"
    restart: unless-stopped
    env_file:
      - cloudwatch.env
    build: images/core
    depends_on:
      - db
    volumes:
      #- "./data/core:/app"
      - "/var/run/docker.sock:/var/run/docker.sock"
  apache:
    user: "0"
    restart: unless-stopped
    build: images/apache
    ports:
      - "822:80"
    #volumes:
    #- ./data/html:/var/www/html/
  db:
    restart: unless-stopped
    image: mysql:8
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./data/mysql:/var/lib/mysql
  phpmyadmin:
    restart: unless-stopped
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 823:80
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
